<?php

namespace App\API\V1\Repositories;
use App\Repositories\Repository;
use App\API\V1\Entities\Album;

/** @noinspection LongInheritanceChainInspection */

/**
 * AlbumRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class AlbumRepository extends Repository
{
    protected /** @noinspection ClassOverridesFieldOfSuperClassInspection */
        $entity = Album::class;

    /**
     * @return array
     */
    public function getTTConfig(): array
    {
        return [
            'default'=>[]
        ];
    }
}
