<?php

namespace App\API\V1\Repositories;

use App\API\V1\Entities\Artist;
use App\Repositories\Repository;

/** @noinspection LongInheritanceChainInspection */


/**
 * ArtistRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class ArtistRepository extends Repository
{
    protected /** @noinspection ClassOverridesFieldOfSuperClassInspection */
        $entity = Artist::class;

    /**
     * @return array
     */
    public function getTTConfig(): array
    {
        return [
            'default'=>[],
            'testing'=>[]
        ];
    }
}
