<?php

namespace App\API\V1\Repositories;

use TempestTools\Crud\Doctrine\RepositoryAbstract;


/**
 * ArtistRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class ArtistRepository extends RepositoryAbstract
{
}
